# ディレクトリ別ラベリング
admin:
  - changed-files:
    - any-glob-to-any-file: 'admin/**'

web:
  - changed-files:
    - any-glob-to-any-file: 'web/**'

infra:
  - changed-files:
    - any-glob-to-any-file: 'infra/**'

api-server:
  - changed-files:
    - any-glob-to-any-file: 'api-server/**'

github-actions:
  - changed-files:
    - any-glob-to-any-file: '.github/**'

# ブランチ名別ラベリング
feature:
  - head-branch: ['^feat']

enhancement:
  - head-branch: ['^enh']

bug:
  - head-branch: ['^fix']

refactor:
  - head-branch: ['^refactor'] 

documentation:
  - head-branch: ['^docs']

ci:
  - head-branch: ['^ci']
