version: '3'

services:
  mongo:
    image: mongo:latest
    restart: always # コンテナが何らかの理由で終了した場合、自動で再起動する
    container_name: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - ./container_data/db:/data/db
      - ./container_data/configdb:/data/configdb
    networks:
      - my-network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  server:
    build:
      context: .
      dockerfile: Dockerfile
      target: test
    container_name: server
    depends_on:
      mongo:
        condition: service_healthy
    environment:
      - NODE_ENV=test
      - TEST_MONGO_URI=mongodb://root:password@mongo:27017/test_db
    volumes:
      - .:/app
      - /app/node_modules  # node_modulesをボリュームとしてマウントして高速化
      - ./coverage:/app/coverage  # カバレッジレポート用
    networks:
      - my-network
    command: npm run test:coverage

networks:
  my-network:
    driver: bridge
