import { Nunito } from 'next/font/google';

import type { Metadata } from 'next';
import './globals.css';
import NextAuthProvider from './providers';

const font = Nunito({
    subsets: ['latin'],
    variable: '--font-nunito',
    weight: ['200', '300', '400', '600', '700', '800', '900'],
});

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <NextAuthProvider>
            <html lang='en'>
                <body className={`${font.variable} antialiased`}>
                    {children}
                </body>
            </html>
        </NextAuthProvider>
    );
}
