# Checkov Configuration
# English Card Battle - Terraform Infrastructure

# フレームワーク設定
framework:
  - terraform
  - terraform_plan

# 除外するチェック（必要に応じて）
skip-check:
  # 開発環境では一部の厳格なルールを除外
  - CKV_AWS_18  # セキュリティグループの説明が必須
  - CKV_AWS_19  # セキュリティグループの名前が必須
  - CKV_AWS_20  # セキュリティグループのルールに説明が必須

# 除外するディレクトリ
skip-path:
  - "**/.terraform/**"
  - "**/node_modules/**"
  - "**/test/**"
  - "**/examples/**"

# 出力形式
output: cli

# 色付き出力
no-color: false

# 詳細出力
verbose: true

# 最小限の重要度
min-cve-severity: MEDIUM

# 外部チェックの設定
external-checks-dir:
  - "aws/test/checkov"

# レポート出力
output-file-path: "checkov-report.json"

# 重要度別の設定
severity:
  CRITICAL: true
  HIGH: true
  MEDIUM: true
  LOW: false 
