import '@/css/style.css'
import NextTopLoader from 'nextjs-toploader'
import { PropsWithChildren } from 'react'

import Providers from './providers'
import Header from '../components/layout/header/Header'
import Sidebar from '../components/layout/sidebar/Sidebar'

import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const RootLayout = ({children,}: PropsWithChildren) => {
  return (
    <html lang="ja" suppressHydrationWarning>
      <body>
        <Providers>
          <NextTopLoader color="#5750F1" showSpinner={false} />

          <div className="flex min-h-screen">
            <Sidebar />

            <div className="w-full bg-gray-2 dark:bg-[#020d1a]">
              <Header />


              <main className="isolate mx-auto w-full max-w-screen-2xl overflow-hidden p-4 md:p-6 2xl:p-10">
                {children}
              </main>

            </div>
          </div>
          
        </Providers>
        
      </body>
    </html>
  )
}
export default RootLayout
