name: 🛡️ CDK Policy Check
on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: "チェックする環境を選択してください"
        default: "dev"
        required: true
        options:
          - dev
          - stg
          - prd
permissions:
  contents: read
defaults:
  run:
    shell: bash
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  nag-check:
    name: 🛡️ CDK Policy Check
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: 📥 リポジトリをチェックアウト
        uses: actions/checkout@v4

      - name: 🟢 Node.jsのセットアップ
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: infra/cdk/package-lock.json
      
      - name: 📦 依存関係をインストール
        working-directory: infra/cdk
        run: npm ci

      - name: 🛡️ CDK Policy Check
        working-directory: infra/cdk
        run: npm run nag-check:${{ inputs.environment }}
